---

- fail: msg="'dbname' is mandatory"
  when: dbname is undefined or not dbname

# detele the database

- name: "Kill active connection to database"
  community.general.postgresql_query:
    db: meta
    query: SELECT
        pg_terminate_backend(pg_stat_activity.pid)
      FROM
        pg_stat_activity
      WHERE
        pg_stat_activity.datname = %(dbname)s
        AND pid <> pg_backend_pid()
    named_args:
      dbname: "{{ dbname }}"
    login_user: root

- name: Drop the database {{ dbname }}
  community.general.postgresql_db:
    name: "{{ dbname }}"
    state: absent
    login_user: root

# remove filestore

- name: Recursively remove filestore of {{ dbname }}
  file:
    path: /home/{{ odoo_user }}/.local/share/Odoo/filestore/{{ dbname }}
    state: absent

# unregister

- name: "Metabase: Remove domains of {{ dbname }}"
  community.general.postgresql_query:
    db: meta
    query: DELETE FROM domain WHERE service_id IN (SELECT id FROM odoo_database WHERE name = %(dbname)s)
    named_args:
      dbname: "{{ dbname }}"
    login_user: root


- name: "Metabase: Remove database {{ dbname }} entry"
  community.general.postgresql_query:
    db: meta
    query: DELETE FROM odoo_database WHERE name = %(dbname)s
    named_args:
      dbname: "{{ dbname }}"
    login_user: root
