---
- name: Setup Odoo Server
  hosts: odoo-cloud
  remote_user: root
  vars:
    user: odoo

  tasks:

    # Common pkg dependencies

    - name: Installation de Libs
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - debconf-utils
        - git
        - htop
        - jq
        - nginx
        - postgresql
        - postgresql-contrib
        - vim
        - xz-utils


    # Docker

    - name: Install Dependencies for Docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Adding GPG keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Backup directory

    - name: Directory for backups
      file:
        path: /home/backup
        state: directory

    # Setup Odoo

    - name: Setup Odoo
      include_role:
        name: odoo-setup

    # Setup Web

    # Metabase

    - name: "Include metabase playbook"
      import_playbook: commmon-metabase.yml
