---
# create unix user
- name: "Create unix user {{ user }}"
  group:
   name: "{{ user }}"
   uid: "{{ user_uid }}"
   group: "{{ user }}"
   state: present
   shell: /bin/bash
   create_home: yes
   generate_ssh_key: no # handle manually after
   state: present

# Note the following is inpired from https://github.com/asifmahmud/ansible-git-clone

# create SSH private key for user
- name: Check if ssh key is already present
  stat:
    path: "/home/{{ user }}/.ssh/id_rsa"
  register: key_stat_result

- name: Generate SSH key for accessing GitHub
  command: "ssh-keygen -t rsa -f /home/{{ user }}/.ssh/id_rsa -N ''"
  when: not key_stat_result.stat.exists

# create 'known_hosts'
- name: Check if known_host exists
  stat:
    path: "/home/{{ user }}/.ssh/known_hosts"
  register: known_hosts_stat

- name: Create known_hosts if it doesn't exist
  file:
    path: "/home/{{ user }}/.ssh/known_hosts"
    state: touch
  when: not known_hosts_stat.stat.exists
