---
# tasks file for odoo-deploy-version: create and enable the service file

- name: Create symbolic link for server file
  become: yes
  become_user: "{{ user }}"
  file:
    src: "/home/{{ user }}/bin/openerp"
    dest: "/home/{{ user }}/bin/openerp-{{ version }}"
    state: link

- name: "Create service file"
  become: yes
  template: src=templates/odoo-service.j2 dest=/etc/systemd/system/openerp-{{ version }}.service owner=root group=root mode='0644'

- name: Enable service Odoo
  service:
    name: openerp-{{ version }}
    enabled: yes

- name: Start service Odoo
  service:
    name: openerp-{{ version }}
    state: started


# FIX ME : this does not work as python-ldap requires more dependencies
- name: Install python requirements
  become: yes
  pip:
    requirements: "/home/{{ user }}/src/odoo/{{ version }}/requirements.txt"
    executable: pip3
