---

- name: "Extract odoo port for {{ version }}"
  shell:
    cmd: python /home/{{ user }}/bin/odoo_get_port.py {{ version }}
  register: portstatus

- name: "Extract odoo longpolling port for {{ version }}"
  shell:
    cmd: python /home/{{ user }}/bin/odoo_get_port.py {{ version }} --longpolling
  register: longpollingportstatus

- name: "Create nginx config file {{ domain }}"
  become: yes
  template: src=templates/nginx-odoo.j2 dest=/etc/nginx/sites-available/{{ domain }} owner=root group=root mode='0644' force=yes
  vars:
    - port: "{{ portstatus.stdout }}"
    - longpollingport: "{{ longpollingportstatus.stdout }}"
    - dbname: dbname
    - version: version

- name: "Enable nginx config {{ domain }}"
  become: yes
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  notify: nginx reload
